$! 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990818_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r081899.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990819_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r081999.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990820_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082099.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990821_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082199.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990822_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082299.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990823_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082399.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990824_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082499.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990825_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082599.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990826_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082699.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990827_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082799.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990828_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082899.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990829_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r082999.dat
n 
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990830_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r083099.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990831_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r083199.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990901_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090199.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990902_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090299.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990903_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090399.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990904_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090499.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990905_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090599.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990906_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090699.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990907_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090799.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990908_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090899.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990909_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r090999.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990910_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091099.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990911_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091199.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990912_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091299.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990913_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091399.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990914_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091499.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990915_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091599.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990916_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091699.dat
n
$run  sms1:[wind.software.stics]WSTICS_RATES.EXE
data_dir:WI_L1_SMS_19990917_V01.DAT
y
-1/
1 
-1/
SMSDISK4:[WIND.L2DATA.STICS]r091799.dat
n
