$!                  
$run  sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980101_V01.DAT
y
n
n
eqtof980101.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980102_V01.DAT
y
n
n
eqtof980102.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980103_V01.DAT
y
n
n
eqtof980103.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980104_V01.DAT
y
n
n
eqtof980104.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980105_V01.DAT
y
n
n
eqtof980105.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980106_V01.DAT
y
n
n
eqtof980106.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980107_V01.DAT
y
n
n
eqtof980107.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980108_V01.DAT
y
n
n
eqtof980108.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980109_V01.DAT
y
n
n
eqtof980109.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980110_V01.DAT
y
n
n
eqtof980110.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980111_V01.DAT
y
n
n
eqtof980111.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980112_V01.DAT
y
n
n
eqtof980112.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980113_V01.DAT
y
n
n
eqtof980113.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980114_V01.DAT
y
n
n
eqtof980114.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980115_V01.DAT
y
n
n
eqtof980115.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980116_V01.DAT
y
n
n
eqtof980116.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980117_V01.DAT
y
n
n
eqtof980117.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980118_V01.DAT
y
n
n
eqtof980118.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980119_V01.DAT
y
n
n
eqtof980119.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980120_V01.DAT
y
n
n
eqtof980120.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980121_V01.DAT
y
n
n
eqtof980121.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980122_V01.DAT
y
n
n
eqtof980122.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980123_V01.DAT
y
n
n
eqtof980123.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980124_V01.DAT
y
n
n
eqtof980124.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980125_V01.DAT
y
n
n
eqtof980125.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980126_V01.DAT
y
n
n
eqtof980126.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980127_V01.DAT
y
n
n
eqtof980127.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980128_V01.DAT
y
n
n
eqtof980128.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980129_V01.DAT
y
n
n
eqtof980129.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980130_V01.DAT
y
n
n
eqtof980130.dat
-1/
n
$run sms1:[wind.software.stics]STX_MMQ_TABLE.EXE	
data_dir:WI_L1_SMS_19980131_V01.DAT
y
n
n
eqtof980131.dat
-1/
n
